apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: PostgreSQL
    url: deep-observer-postgres:5432
    database: deepobserver
    user: deepobserver
    isDefault: true
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      database: deepobserver
    secureJsonData:
      password: 'deepobserver'

  - name: Prometheus
    type: prometheus
    uid: Prometheus
    url: http://deep-observer-prometheus:9090
    access: proxy
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: Tempo
          name: traceID

  - name: Loki
    type: loki
    uid: Loki
    url: http://deep-observer-loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - datasourceUid: Tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  - name: Tempo
    type: tempo
    uid: Tempo
    url: http://deep-observer-tempo:3200
    access: proxy
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: 'Prometheus'
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: 'Loki'
