# Build stage
FROM golang:1.25 AS builder

WORKDIR /app

# cache deps
COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /bin/control-plane-api ./cmd/server

# Runtime stage
FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /bin/control-plane-api /app/control-plane-api

EXPOSE 8090
USER nonroot:nonroot

ENTRYPOINT [ "/app/control-plane-api" ]
